/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScsAmbulanceWlList {
    }
}
declare global {
    interface HTMLScsAmbulanceWlListElement extends Components.ScsAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLScsAmbulanceWlListElement: {
        prototype: HTMLScsAmbulanceWlListElement;
        new (): HTMLScsAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "scs-ambulance-wl-list": HTMLScsAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface ScsAmbulanceWlList {
    }
    interface IntrinsicElements {
        "scs-ambulance-wl-list": ScsAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scs-ambulance-wl-list": LocalJSX.IntrinsicElements["scs-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLScsAmbulanceWlListElement>;
        }
    }
}
